### ISSUE TITLE
Add cookie consent to website

### ISSUE THREAD

**Issue by natsteinmetz** [shescoding/conference-website#6]
Add a cookie consent to the website. Make sure the cookie consent does not reappear every time a person visits the site. Feel free to use a JavaSript plugin like [this](https://cookieconsent.insites.com/) and style it in the colors of our website. The color codes can be found on the application.css file.

**Comment by dylmye** [comment]
I'm happy to take this up! :)

**Comment by natsteinmetz** [comment]
Sounds good, thanks @dylmye
